### ISSUE TITLE
Setup eslint and editorconfig 

### ISSUE THREAD

**Issue by RabeDatta** [BayardoZelaya/Career-Spotter-bot#1]
Let's setup eslint and .editorconfig in the project. 

Add a lint command to our package.json scripts section as well, so that we can run ```npm run lint``` to have eslint run over the project.

.editorconfig is a universal subset of configuration for all text editors. More information [here ](https://editorconfig.org/#overview)

**Comment by RickyC0626** [comment]
Merged
